# Generated by Django 5.2.12 on 2026-03-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=30)),
                ('destinatario', models.CharField(max_length=255)),
                ('asunto', models.CharField(blank=True, max_length=255)),
                ('mensaje', models.TextField()),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('referencia_entidad', models.CharField(blank=True, max_length=100)),
                ('referencia_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['estado_envio'], name='idx_notificaciones_estado')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estado_envio__in', ['PENDIENTE', 'ENVIADO', 'ERROR', 'CANCELADO'])), name='chk_notificaciones_estado')],
            },
        ),
    ]
