# Generated by Django 5.2.12 on 2026-03-24 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500)),
                ('tipo_importacion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('CARGADO', 'Cargado'), ('PROCESADO', 'Procesado'), ('VALIDADO', 'Validado'), ('IMPORTADO', 'Importado'), ('ERROR', 'Error')], default='CARGADO', max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('total_ok', models.IntegerField(default=0)),
                ('total_error', models.IntegerField(default=0)),
                ('fecha_proceso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_pdf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'importacion PDF',
                'verbose_name_plural': 'importaciones PDF',
                'db_table': 'importaciones_pdf',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionPDFDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nro_linea', models.IntegerField(blank=True, null=True)),
                ('tipo_registro', models.CharField(blank=True, max_length=50)),
                ('dato_original', models.TextField(blank=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('procesado_ok', models.BooleanField(default=False)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pdf_imports.importacionpdf')),
            ],
            options={
                'verbose_name': 'detalle de importacion PDF',
                'verbose_name_plural': 'detalles de importacion PDF',
                'db_table': 'importacion_pdf_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='importacionpdf',
            index=models.Index(fields=['estado'], name='idx_importaciones_pdf_estado'),
        ),
        migrations.AddConstraint(
            model_name='importacionpdf',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['CARGADO', 'PROCESADO', 'VALIDADO', 'IMPORTADO', 'ERROR'])), name='chk_importaciones_pdf_estado'),
        ),
    ]
