# Generated by Django 5.2.12 on 2026-03-24 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=100)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auditoria',
                'verbose_name_plural': 'auditoria',
                'db_table': 'auditoria',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='idx_audit_entidad_ent_id'), models.Index(fields=['fecha_hora'], name='idx_auditoria_fecha_hora')],
            },
        ),
    ]
