# Generated by Django 5.2.12 on 2026-03-24 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono_responsable', models.CharField(blank=True, max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
                'db_table': 'alumnos',
                'ordering': ['apellidos', 'nombres'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sexo__isnull', True), ('sexo__in', ['M', 'F', 'OTRO']), _connector='OR'), name='chk_alumnos_sexo')],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('seccion', models.CharField(max_length=30)),
                ('turno', models.CharField(max_length=30)),
                ('periodo_lectivo', models.CharField(max_length=30)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('grado', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'cursos',
                'ordering': ['periodo_lectivo', 'nombre', 'seccion', 'turno'],
                'indexes': [models.Index(fields=['periodo_lectivo'], name='idx_cursos_periodo_lectivo'), models.Index(fields=['nombre'], name='idx_cursos_nombre')],
                'constraints': [models.UniqueConstraint(fields=('codigo', 'periodo_lectivo', 'seccion', 'turno'), name='uq_curso_cod_per_sec_turno')],
            },
        ),
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('TRASLADADO', 'Trasladado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academics.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='academics.curso')),
            ],
            options={
                'verbose_name': 'matricula de alumno',
                'verbose_name_plural': 'matriculas de alumnos',
                'db_table': 'alumno_curso',
                'ordering': ['-fecha_ingreso'],
                'indexes': [models.Index(fields=['alumno'], name='idx_alumno_curso_alumno'), models.Index(fields=['curso'], name='idx_alumno_curso_curso')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_salida__isnull', True), ('fecha_salida__gte', models.F('fecha_ingreso')), _connector='OR'), name='chk_alumno_curso_fechas'), models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVO', 'RETIRADO', 'TRASLADADO', 'FINALIZADO'])), name='chk_alumno_curso_estado'), models.UniqueConstraint(fields=('alumno', 'curso', 'fecha_ingreso'), name='uq_alumno_curso')],
            },
        ),
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('titular', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='academics.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to='accounts.profesor')),
            ],
            options={
                'verbose_name': 'asignacion profesor-curso',
                'verbose_name_plural': 'asignaciones profesor-curso',
                'db_table': 'profesor_curso',
                'ordering': ['-fecha_desde'],
                'indexes': [models.Index(fields=['profesor'], name='idx_profesor_curso_profesor'), models.Index(fields=['curso'], name='idx_profesor_curso_curso')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_hasta__isnull', True), ('fecha_hasta__gte', models.F('fecha_desde')), _connector='OR'), name='chk_profesor_curso_fechas'), models.UniqueConstraint(fields=('profesor', 'curso', 'fecha_desde'), name='uq_profesor_curso')],
            },
        ),
    ]
