# Generated by Django 5.2.12 on 2026-03-24 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('estado_control', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTROLADA', 'Controlada'), ('CORREGIDA', 'Corregida')], default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asistencias', to='academics.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asistencias', to='accounts.profesor')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'db_table': 'asistencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], default='PRESENTE', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('corregido', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='asistencias', to='academics.alumno')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='attendance.asistencia')),
            ],
            options={
                'verbose_name': 'detalle de asistencia',
                'verbose_name_plural': 'detalles de asistencia',
                'db_table': 'asistencia_detalle',
                'ordering': ['alumno__apellidos', 'alumno__nombres'],
            },
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['fecha'], name='idx_asistencias_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['curso', 'fecha'], name='idx_asistencias_curso_fecha'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.CheckConstraint(condition=models.Q(('estado_control__in', ['BORRADOR', 'CONTROLADA', 'CORREGIDA'])), name='chk_asistencias_estado'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('curso', 'profesor', 'fecha'), name='uq_asis_cur_prof_fecha'),
        ),
        migrations.AddIndex(
            model_name='asistenciadetalle',
            index=models.Index(fields=['alumno'], name='idx_asistencia_detalle_alumno'),
        ),
        migrations.AddConstraint(
            model_name='asistenciadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PRESENTE', 'AUSENTE', 'JUSTIFICADO'])), name='chk_asistencia_detalle_estado'),
        ),
        migrations.AddConstraint(
            model_name='asistenciadetalle',
            constraint=models.UniqueConstraint(fields=('asistencia', 'alumno'), name='uq_asistencia_detalle'),
        ),
    ]
